version: '3.1'
services:
  mysql:
    image: mysql:8.0.29
    container_name: luni-mysql
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin-pwd
      MYSQL_DATABASE: lunapi
      MYSQL_USER: luni-admin
      MYSQL_PASSWORD: luni-admin-api
      TZ: Europe/Paris
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  api:
    image: node:16.16.0
    container_name: luni-api
    ports:
      - 50000:5000
    volumes:
      - ./luni-api:/usr/luni/api
    environment:
      MYSQL_DATABASE_PORT: 33306
      MYSQL_DATABASE_NAME: lunapi
      NODE_PORT: 5000
    user: "node"
    working_dir: /usr/luni/api
    command: "npm run dev"
    restart: on-failure
    
