version: '3.1'
services:
  luni-mysql:
    image: mysql:5.7.38
    environment:
      MYSQL_ROOT_PASSWORD: admin-pwd
      MYSQL_DATABASE: lunapi
      MYSQL_USER: luni-admin
      MYSQL_PASSWORD: luni-admin-api
      TZ: Europe/Paris
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./conf/luni_mysql.cnf:/etc/mysql/luni_mysql.cnf
      - ./mysql-data:/var/lib/mysql
    command: ["--max_connections=2000"]
    deploy:
      mode: replicated
      replicas: 3
    networks:
      luninet:
  luni-redis:
    image: redis/redis-stack-server:6.2.2-v5
    deploy:
      mode: replicated
      replicas: 2
    networks:
      luninet:
  luni-api:
    image: node:16.16.0
    volumes:
      - ./luni-api:/usr/luni/api
    environment:
      MYSQL_HOSTNAME: 'luni-mysql'
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_NAME: lunapi
      MYSQL_USER: luni-admin
      MYSQL_PASSWORD: luni-admin-api
      NODE_PORT: 5000
      REDIS_HOSTNAME: 'luni-redis'
    user: "node"
    working_dir: /usr/luni/api
    command: "npm run dev"
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 5
    networks:
      luninet:
  nginx:
    image: nginx:stable-alpine
    container_name: luni-nginx
    ports:
      - 8000:80
    depends_on:
      - luni-api
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      luninet:
networks:
  luninet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.1/24"
