version: '3.1'
services:
  mysql:
    image: mysql:5.7.38
    container_name: luni-mysql
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin-pwd
      MYSQL_DATABASE: lunapi
      MYSQL_USER: luni-admin
      MYSQL_PASSWORD: luni-admin-api
      TZ: Europe/Paris
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./conf/luni_mysql.cnf:/etc/mysql/luni_mysql.cnf
    command: ["--max_connections=2000"]
    networks:
      luninet:
        ipv4_address: 172.22.0.254
  luni-api:
    image: node:16.16.0
    volumes:
      - ./luni-api:/usr/luni/api
    environment:
      MYSQL_DATABASE_PORT: 33306
      MYSQL_DATABASE_NAME: lunapi
      MYSQL_USER: luni-admin
      MYSQL_PASSWORD: luni-admin-api
      NODE_PORT: 5000
    user: "node"
    working_dir: /usr/luni/api
    command: "npm run dev"
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 5 
    networks:
      luninet:
  nginx:
    image: nginx:stable-alpine
    container_name: luni-nginx
    ports:
      - 8000:80
    depends_on:
      - luni-api
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      luninet:
networks:
  luninet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.1/24"
